definitions:
  models.Task:
    properties:
      description:
        type: string
      id:
        type: integer
      is_complete:
        type: boolean
      task_name:
        type: string
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /task:
    get:
      consumes:
      - application/json
      description: list tasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Task'
            type: array
      summary: Get a list of tasks
      tags:
      - example
  /user:
    get:
      consumes:
      - application/json
      description: list users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
      summary: Get all users in example service
      tags:
      - example
swagger: "2.0"
