// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"SampleGoService/src/controllers"
	"SampleGoService/src/db"
)

// Injectors from wire.go:

func CreateUserController() controllers.UserController {
	userDao := db.NewUserDao()
	userController := controllers.NewUserController(userDao)
	return userController
}
